name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0
      - run: pnpm install
      - env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
        run: pnpm run release
